/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CategoryWhereUniqueInput } from "../../category/base/CategoryWhereUniqueInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { CommentUpdateManyWithoutListingsInput } from "./CommentUpdateManyWithoutListingsInput";
import { ListingImageUpdateManyWithoutListingsInput } from "./ListingImageUpdateManyWithoutListingsInput";
import { ProfileWhereUniqueInput } from "../../profile/base/ProfileWhereUniqueInput";

@InputType()
class ListingUpdateInput {
  @ApiProperty({
    required: false,
    type: () => CategoryWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CategoryWhereUniqueInput)
  @IsOptional()
  @Field(() => CategoryWhereUniqueInput, {
    nullable: true,
  })
  category?: CategoryWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => CommentUpdateManyWithoutListingsInput,
  })
  @ValidateNested()
  @Type(() => CommentUpdateManyWithoutListingsInput)
  @IsOptional()
  @Field(() => CommentUpdateManyWithoutListingsInput, {
    nullable: true,
  })
  comments?: CommentUpdateManyWithoutListingsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  coverImage?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => ListingImageUpdateManyWithoutListingsInput,
  })
  @ValidateNested()
  @Type(() => ListingImageUpdateManyWithoutListingsInput)
  @IsOptional()
  @Field(() => ListingImageUpdateManyWithoutListingsInput, {
    nullable: true,
  })
  listingImages?: ListingImageUpdateManyWithoutListingsInput;

  @ApiProperty({
    required: false,
    type: () => ProfileWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ProfileWhereUniqueInput)
  @IsOptional()
  @Field(() => ProfileWhereUniqueInput, {
    nullable: true,
  })
  owner?: ProfileWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string;
}

export { ListingUpdateInput as ListingUpdateInput };
