/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CategoryWhereUniqueInput } from "../../category/base/CategoryWhereUniqueInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { CommentCreateNestedManyWithoutListingsInput } from "./CommentCreateNestedManyWithoutListingsInput";
import { ListingImageCreateNestedManyWithoutListingsInput } from "./ListingImageCreateNestedManyWithoutListingsInput";
import { ProfileWhereUniqueInput } from "../../profile/base/ProfileWhereUniqueInput";

@InputType()
class ListingCreateInput {
  @ApiProperty({
    required: false,
    type: () => CategoryWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CategoryWhereUniqueInput)
  @IsOptional()
  @Field(() => CategoryWhereUniqueInput, {
    nullable: true,
  })
  category?: CategoryWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => CommentCreateNestedManyWithoutListingsInput,
  })
  @ValidateNested()
  @Type(() => CommentCreateNestedManyWithoutListingsInput)
  @IsOptional()
  @Field(() => CommentCreateNestedManyWithoutListingsInput, {
    nullable: true,
  })
  comments?: CommentCreateNestedManyWithoutListingsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  coverImage?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => ListingImageCreateNestedManyWithoutListingsInput,
  })
  @ValidateNested()
  @Type(() => ListingImageCreateNestedManyWithoutListingsInput)
  @IsOptional()
  @Field(() => ListingImageCreateNestedManyWithoutListingsInput, {
    nullable: true,
  })
  listingImages?: ListingImageCreateNestedManyWithoutListingsInput;

  @ApiProperty({
    required: true,
    type: () => ProfileWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ProfileWhereUniqueInput)
  @Field(() => ProfileWhereUniqueInput)
  owner!: ProfileWhereUniqueInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  title!: string;
}

export { ListingCreateInput as ListingCreateInput };
