/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GrpcMethod } from "@nestjs/microservices";
import { ListingImageService } from "../listingImage.service";
import { Public } from "../../decorators/public.decorator";
import { ListingImageCreateInput } from "./ListingImageCreateInput";
import { ListingImageWhereInput } from "./ListingImageWhereInput";
import { ListingImageWhereUniqueInput } from "./ListingImageWhereUniqueInput";
import { ListingImageFindManyArgs } from "./ListingImageFindManyArgs";
import { ListingImageUpdateInput } from "./ListingImageUpdateInput";
import { ListingImage } from "./ListingImage";
import { ListingFindManyArgs } from "../../listing/base/ListingFindManyArgs";
import { Listing } from "../../listing/base/Listing";
import { ListingWhereUniqueInput } from "../../listing/base/ListingWhereUniqueInput";

export class ListingImageGrpcControllerBase {
  constructor(protected readonly service: ListingImageService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ListingImage })
  @GrpcMethod("ListingImageService", "create")
  async create(
    @common.Body() data: ListingImageCreateInput
  ): Promise<ListingImage> {
    return await this.service.create({
      data: data,
      select: {
        altText: true,
        createdAt: true,
        id: true,
        order: true,
        updatedAt: true,
        url: true,
      },
    });
  }

  @Public()
  @common.Get()
  @swagger.ApiOkResponse({ type: [ListingImage] })
  @ApiNestedQuery(ListingImageFindManyArgs)
  @GrpcMethod("ListingImageService", "findMany")
  async findMany(@common.Req() request: Request): Promise<ListingImage[]> {
    const args = plainToClass(ListingImageFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        altText: true,
        createdAt: true,
        id: true,
        order: true,
        updatedAt: true,
        url: true,
      },
    });
  }

  @Public()
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ListingImage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("ListingImageService", "findOne")
  async findOne(
    @common.Param() params: ListingImageWhereUniqueInput
  ): Promise<ListingImage | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        altText: true,
        createdAt: true,
        id: true,
        order: true,
        updatedAt: true,
        url: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ListingImage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("ListingImageService", "update")
  async update(
    @common.Param() params: ListingImageWhereUniqueInput,
    @common.Body() data: ListingImageUpdateInput
  ): Promise<ListingImage | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          altText: true,
          createdAt: true,
          id: true,
          order: true,
          updatedAt: true,
          url: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ListingImage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("ListingImageService", "delete")
  async delete(
    @common.Param() params: ListingImageWhereUniqueInput
  ): Promise<ListingImage | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          altText: true,
          createdAt: true,
          id: true,
          order: true,
          updatedAt: true,
          url: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @Public()
  @common.Get("/:id/listing")
  @ApiNestedQuery(ListingFindManyArgs)
  @GrpcMethod("ListingImageService", "findManyListing")
  async findManyListing(
    @common.Req() request: Request,
    @common.Param() params: ListingImageWhereUniqueInput
  ): Promise<Listing[]> {
    const query = plainToClass(ListingFindManyArgs, request.query);
    const results = await this.service.findListing(params.id, {
      ...query,
      select: {
        category: {
          select: {
            id: true,
          },
        },

        coverImage: true,
        createdAt: true,
        description: true,
        id: true,

        owner: {
          select: {
            id: true,
          },
        },

        title: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/listing")
  @GrpcMethod("ListingImageService", "connectListing")
  async connectListing(
    @common.Param() params: ListingImageWhereUniqueInput,
    @common.Body() body: ListingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      listing: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/listing")
  @GrpcMethod("ListingImageService", "updateListing")
  async updateListing(
    @common.Param() params: ListingImageWhereUniqueInput,
    @common.Body() body: ListingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      listing: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/listing")
  @GrpcMethod("ListingImageService", "disconnectListing")
  async disconnectListing(
    @common.Param() params: ListingImageWhereUniqueInput,
    @common.Body() body: ListingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      listing: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
